title = "ReqTool"

[cryptsy]
urlGet = ["crypsty:urls:depth",  "crypsty:urls:depth"]

[btc38]
urlGet = ["btc38:urls:depth",  "btc38:urls:ticker"]

[bter]
urlGet = ["bter:urls:depth",  "bter:urls:ticker"]

[ccedk]
urlGet = ["ccedk:urls:depth",  "ccedk:urls:ticker"]

[poloniex]
urlGet = ["poloniex:urls:depth",  "poloniex:urls:ticker"]